version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
    groups:
      all:
        patterns: ["*"]

    ignore:
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
