language: dart

jobs:
  include:
    - dart: 2.4.0
      name: "SDK: 2.4.0"
      script:
        - dartanalyzer .
    - dart: stable
      name: "SDK: stable"
      script:
        - dartanalyzer .
        - dartfmt -n --set-exit-if-changed .
      name: "SDK: dev"
      script:
        - dartanalyzer .
