name: Check Open Automated PRs
on:
  schedule:
    # runs on weekdays at 5PM UTC
    - cron: '46 17 * * 1-5'

permissions:
  contents: write
  id-token: write

jobs:
  check-prs:
    secrets: inherit
    uses: Workiva/gha-automated-pr-check/.github/workflows/automated-pr-check.yaml@v0.1.3
    with:
      slack-alert-channel: 'C0943S449B3' #support-grc-testing-evidence
