name: CI
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "master" ]
    tags: [ "*" ]

permissions:
  contents: read
  id-token: write

jobs:
  build-pub-package:
    name: Dart library
    runs-on: [self-hosted, medium]
    steps:
      - uses: Workiva/gha-setup-credentials@refs/tags/v1.0.16
      - uses: actions/checkout@v3
      # This pub get is necessary for dependency tracking
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.7
      - uses: Workiva/gha-dart/pub-get@refs/tags/v0.2.10
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          token: ${{ secrets.NPM_TOKEN }}
      - name: Install js
        run: npm install
      - uses: Workiva/gha-dart/create-pub-package@refs/tags/v0.2.10
