name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '**'

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.18.7, 2.19.6 ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - id: install
        name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze
        if: always() && steps.install.outcome == 'success'

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'
