name: Publish to pub.dev

on:
  push:
    tags:
      # Releases
      - '[0-9]+.[0-9]+.[0-9]+'
      # Release Candidates
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      # Build identified release
      - '[0-9]+.[0-9]+.[0-9]+\+[0-9]+'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  create-sbom-release-asset:
    name: Create SBOM Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Publish SBOM to Release Assets
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json

  publish:
    name: Publish to pub.dev
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1.6.5