name: Publish to pub.dev

on:
  push:
    tags:
      # Releases
      - '[0-9]+.[0-9]+.[0-9]+'
      # Release Candidates
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1